
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`include "modules/clk_div.v"
`include "modules/seg7.v"

module DE10_Standard(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT
);


//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [31:0] clk_div;


//=======================================================
//  Structural coding
//=======================================================

	assign LEDR = SW;

	clk_div div0(
		.clk(CLOCK_50),
		.rst(KEY[0]),
		.clk_div(clk_div)
	);

	segment7 seg0(
		.segment0(HEX0),
		.segment1(HEX1),
		.segment2(HEX2),
		.segment3(HEX3),
		.segment4(HEX4),
		.segment5(HEX5),
		.digits(clk_div[31:8])
	);


endmodule
